build-and-push:
    needs: deps-and-test
    uses: edoturb/AUY1104-SharedWorkflows/.github/workflows/build-push-dockerhub.yaml@main
    with:
      docker-username: ${{ vars.DOCKER_USERNAME || 'edoturbina' }}
      image-name: demo-api
      image-tag: ${{ github.sha }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
